# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutingWorkflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WorkflowInstance',
            },
        ),
        migrations.CreateModel(
            name='FlowObject',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SequenceFlow',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('xml', models.TextField()),
                ('status', models.BooleanField()),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Workflow',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('flowobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.FlowObject')),
            ],
            bases=('workflows.flowobject',),
        ),
        migrations.AddField(
            model_name='sequenceflow',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_ref', to='workflows.FlowObject'),
        ),
        migrations.AddField(
            model_name='sequenceflow',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terget_ref', to='workflows.FlowObject'),
        ),
        migrations.AddField(
            model_name='executingworkflow',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.WorkflowForm'),
        ),
        migrations.CreateModel(
            name='StartEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflows.Event')),
            ],
            bases=('workflows.event',),
        ),
        migrations.AddField(
            model_name='executingworkflow',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Event'),
        ),
        migrations.AddField(
            model_name='workflowform',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.StartEvent'),
        ),
    ]
