# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkflowForm',
            new_name='WorkflowTemplate',
        ),
        migrations.AlterModelTable(
            name='executingworkflow',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workflowtemplate',
            table=None,
        ),
    ]
