# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='userType',
            field=models.CharField(default='', max_length=50),
        ),
    ]
