# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_studentmodel_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='profileLogo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
