# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_auto_20161210_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtemplate',
            name='start',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workflows.StartEvent'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='status',
            field=models.CharField(default='Unpublished', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='xml',
            field=models.TextField(default=None),
        ),
    ]
