# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_studentmodel_profilelogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='address',
            new_name='facebookAddress',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='loopId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='tittle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
