# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0004_auto_20161210_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executingworkflow',
            old_name='form',
            new_name='template',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='creator',
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='creator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.StartEvent'),
        ),
    ]
