# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_auto_20161210_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtemplate',
            name='start',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='workflows.StartEvent'),
        ),
    ]
